In [3]:
# Import necessary libraries
import pandas as pd

In [5]:
# Define the URL of the raw data file
url = "https://github.com/MIT-Emerging-Talent/ET6-CDSP-group-08-repo/raw/refs/heads/main/1_datasets/raw_data/UN_Comtrade_imports_dataset_raw.xlsx"
# Read the Excel file into a pandas DataFrame
df = pd.read_excel(url, engine="openpyxl")
# Display the first  rows of the DataFrame
df.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20190101,2019,52,2019,4,AFG,Afghanistan,M,...,0.0,True,0.0,False,89932863.97,0.0,89932863.97,4,False,True
1,C,A,20070101,2007,52,2007,140,CAF,Central African Rep.,M,...,1796.0,False,NaN,False,26489.00,NaN,26489.00,0,True,False
2,C,A,20080101,2008,52,2008,140,CAF,Central African Rep.,M,...,1654.0,False,NaN,False,61941.00,NaN,61941.00,0,True,False
3,C,A,20090101,2009,52,2009,140,CAF,Central African Rep.,M,...,7822.0,False,NaN,False,269897.00,NaN,269897.00,0,True,False
4,C,A,20100101,2010,52,2010,140,CAF,Central African Rep.,M,...,12346.0,False,NaN,False,173026.00,NaN,173026.00,0,True,False

In [6]:
# Display the shape of the DataFrame (number of rows and columns)
df.shape

(781, 47)

In [7]:
# Display information about the DataFrame, including column data types and non-null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 781 entries, 0 to 780
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   typeCode                  781 non-null    object
 1   freqCode                  781 non-null    object
 2   refPeriodId               781 non-null    int64
 3   refYear                   781 non-null    int64
 4   refMonth                  781 non-null    int64
 5   period                    781 non-null    int64
 6   reporterCode              781 non-null    int64
 7   reporterISO               781 non-null    object
 8   reporterDesc              781 non-null    object
 9   flowCode                  781 non-null    object
 10  flowDesc                  781 non-null    object
 11  partnerCode               781 non-null    int64
 12  partnerISO                781 non-null    object
 13  partnerDesc               781 non-null    object
 14  partner2Code              781 non-null    int64
 15  partner2ISO               781 non-null    object
 16  partner2Desc              781 non-null    object
 17  classificationCode        781 non-null    object
 18  classificationSearchCode  781 non-null    object
 19  isOriginalClassification  781 non-null    bool
 20  cmdCode                   781 non-null    int64
 21  cmdDesc                   781 non-null    object
 22  aggrLevel                 781 non-null    int64
 23  isLeaf                    781 non-null    bool
 24  customsCode               781 non-null    object
 25  customsDesc               781 non-null    object
 26  mosCode                   781 non-null    int64
 27  motCode                   781 non-null    int64
 28  motDesc                   781 non-null    object
 29  qtyUnitCode               781 non-null    int64
 30  qtyUnitAbbr               309 non-null    object
 31  qty                       591 non-null    float64
 32  isQtyEstimated            781 non-null    bool
 33  altQtyUnitCode            781 non-null    int64
 34  altQtyUnitAbbr            326 non-null    object
 35  altQty                    484 non-null    float64
 36  isAltQtyEstimated         781 non-null    bool
 37  netWgt                    677 non-null    float64
 38  isNetWgtEstimated         781 non-null    bool
 39  grossWgt                  432 non-null    float64
 40  isGrossWgtEstimated       781 non-null    bool
 41  cifvalue                  781 non-null    float64
 42  fobvalue                  164 non-null    float64
 43  primaryValue              781 non-null    float64
 44  legacyEstimationFlag      781 non-null    int64
 45  isReported                781 non-null    bool
 46  isAggregate               781 non-null    bool
dtypes: bool(8), float64(7), int64(14), object(18)
memory usage: 244.2+ KB

In [8]:
# Display the column names of the DataFrame
df.columns

Index(['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth', 'period',
       'reporterCode', 'reporterISO', 'reporterDesc', 'flowCode', 'flowDesc',
       'partnerCode', 'partnerISO', 'partnerDesc', 'partner2Code',
       'partner2ISO', 'partner2Desc', 'classificationCode',
       'classificationSearchCode', 'isOriginalClassification', 'cmdCode',
       'cmdDesc', 'aggrLevel', 'isLeaf', 'customsCode', 'customsDesc',
       'mosCode', 'motCode', 'motDesc', 'qtyUnitCode', 'qtyUnitAbbr', 'qty',
       'isQtyEstimated', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty',
       'isAltQtyEstimated', 'netWgt', 'isNetWgtEstimated', 'grossWgt',
       'isGrossWgtEstimated', 'cifvalue', 'fobvalue', 'primaryValue',
       'legacyEstimationFlag', 'isReported', 'isAggregate'],
      dtype='object')

In [9]:
# Define a list of columns to be dropped
columns_to_drop = [
    "typeCode",
    "freqCode",
    "refPeriodId",
    "refMonth",
    "period",
    "reporterCode",
    "flowCode",
    "flowDesc",
    "partnerCode",
    "partnerDesc",
    "partner2Desc",
    "partnerISO",
    "partner2Code",
    "partner2Code",
    "partner2ISO",
    "classificationCode",
    "classificationSearchCode",
    "isOriginalClassification",
    "aggrLevel",
    "isLeaf",
    "customsCode",
    "customsDesc",
    "mosCode",
    "motCode",
    "motDesc",
    "qtyUnitCode",
    "qtyUnitAbbr",
    "isQtyEstimated",
    "altQtyUnitCode",
    "altQtyUnitAbbr",
    "altQty",
    "isAltQtyEstimated",
    "isNetWgtEstimated",
    "grossWgt",
    "isGrossWgtEstimated",
    "cifvalue",
    "fobvalue",
    "qty",
    "legacyEstimationFlag",
    "isReported",
    "isAggregate",
]
# Drop the specified columns from the DataFrame and create a new DataFrame
new_df = df.drop(columns=columns_to_drop)

In [10]:
# Display the column names of the new DataFrame
new_df.columns

Index(['refYear', 'reporterISO', 'reporterDesc', 'cmdCode', 'cmdDesc',
       'netWgt', 'primaryValue'],
      dtype='object')

In [11]:
# Display the shape of the new DataFrame
new_df.shape

(781, 7)

In [16]:
# Rename the columns for clarity
new_df.rename(
    columns={
        "refYear": "Year",
        "reporterISO": "ISO_Code",
        "reporterDesc": "Country",
        "cmdCode": "Product_Code",
        "cmdDesc": "Product_Description",
        "netWgt": "Net_Weight_kg",
        "primaryValue": "Value_USD",
    },
    inplace=True,
)

# Display the first 5 rows of the DataFrame with the new column names
new_df.head()

,Year,\tISO_Code,Country,Product_Code,Product_Description,Net_Weight_kg,Value_USD
0,2019,AFG,Afghanistan,854140,"Electrical apparatus; photosensitive, includin...",0.0,89932863.97
1,2007,CAF,Central African Rep.,854140,"Electrical apparatus; photosensitive, includin...",1796.0,26489.00
2,2008,CAF,Central African Rep.,854140,"Electrical apparatus; photosensitive, includin...",1654.0,61941.00
3,2009,CAF,Central African Rep.,854140,"Electrical apparatus; photosensitive, includin...",7822.0,269897.00
4,2010,CAF,Central African Rep.,854140,"Electrical apparatus; photosensitive, includin...",12346.0,173026.00

In [17]:
# Display the column names of the DataFrame after renaming
new_df.columns

Index(['Year', '\tISO_Code', 'Country', 'Product_Code', 'Product_Description',
       'Net_Weight_kg', 'Value_USD'],
      dtype='object')

In [29]:
# Save the cleaned DataFrame to an Excel file
new_df.to_excel("cleaned_comtrade_data.xlsx", index=False)